### ISSUE TITLE
Inconsistent file names in https://data.sdss5.org/sas/sdsswork/target/development/0.5.0/

### ISSUE THREAD

**Issue by BGaensicke** [sdss/target_selection#60]
The file name convention seems to have changed at some point, 

`mwm_cb_300pc_boss_0.5.0_targetdb.fits` vs `mwm_wd_core-targetdb-0.5.0.fits`

This may lead to some confusing when re-downloading files / doing some automated checks.

**Comment by albireox** [comment]
Yes, unfortunately I wasn't super consistent when generating the files. We'll try to keep the files the same if we regenerate them for 0.5.0 and be more consistent for future runs.
